### ISSUE TITLE
crash on janus plugin api version 14 

### ISSUE THREAD

**Issue by arpu** [mozilla/janus-plugin-sfu#46]
```
[8398200112870128] There's a message for Janus SFU plugin
Queueing signalling message on 0x7fff8401aae0.
No auth_key configured. Allowing join from 0x7fff8401aae0 to room 37 as user 4842612465433525.
Processing join-time subscription from 0x7fff8401aae0: Subscription { notifications: false, data: false, media: Some("3462427722628661") }.
[8398200112870128] Audio has been negotiated
[8398200112870128] Video has been negotiated
[8398200112870128] SCTP/DataChannels have been negotiated
[8398200112870128] Setting ICE locally: got ANSWER (1 audios, 1 videos)
[8398200112870128] Creating ICE agent (ICE Full mode, controlling)
[8398200112870128] Adding 10.6.0.169 to the addresses to gather candidates for
[8398200112870128] Component state changed for component 1 in stream 1: 1 (gathering)
[8398200112870128] Waiting for candidates-done callback...

Thread 32 "hloop 784930706" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff7dffb700 (LWP 18075)]
janus_plugin_relay_rtp (plugin_session=0x7fff8401aae0, packet=0x7dfea7c0) at janus.c:3576
3576                            packet == NULL || packet->buffer == NULL || packet->length < 1)
(gdb) bt full
#0  0x000055555559e0df in janus_plugin_relay_rtp (plugin_session=0x7fff8401aae0, packet=0x7dfea7c0) at janus.c:3576
#1  0x00007fffb3d2a881 in janus_plugin_sfu::incoming_rtp () at /opt/janus/lib/janus/plugins/libjanus_plugin_sfu.so
#2  0x00005555555977c8 in janus_ice_cb_nice_recv (agent=<optimized out>, stream_id=<optimized out>, component_id=<optimized out>, len=<optimized out>, buf=0x7fff7dfeaa70 "\200o", ice=0x7fff6401e1a0) at ice.c:2496
        last_seqs = <optimized out>
        header = 0x7fff7dfeaa70
        plen = 66
        payload = 0x7fff7dfeaa7c "x\030d\226.n\321\375ϰ\017&lP\206\213\212z%Q\241LE\214\063\252\223q\222\066\215\353\255au\237F\202\025$=\002\275\226\216\216L$\237\241\301"
        rtp = {video = 0, buffer = 0x7fff7dfeaa70 "\200o", length = 78, extensions = {audio_level = -1 '\377', audio_level_vad = 0, video_rotation = -1, video_back_camera = 0, video_flipped = 0}}
        now = <optimized out>
        backup =
            {csrccount = 0, extension = 0, padding = 0, version = 2, type = 111, markerbit = 0, seq_number = 16469, timestamp = 2932084590, ssrc = 2928453440, csrc = {2523142264, 4258360878, 638562511, 2340835436, 1361410698, 2353351841, 1905502771, 4019009170, 2917900428, 1184855393, 1025774978, 2392243458, 2669956238, 1325449633, 3481830823, 1975102778}}
        new_seqn = <optimized out>
        cur_seqn = <optimized out>
        last_seqs_len = <optimized out>
        plugin = <optimized out>
        rtcp_ctx = <optimized out>
        retransmissions_disabled = <optimized out>
        cur_seq = <optimized out>
        nacks = <optimized out>
        nacks_count = <optimized out>
        video = <optimized out>
        vindex = <optimized out>
        buflen = 78
        header = 0x7fff7dfeaa70
        packet_ssrc = 1084722350
        rtx = <optimized out>
        res = <optimized out>
        component = 0x7fff6401e1a0
        __FUNCTION__ = "janus_ice_cb_nice_recv"
        stream = <optimized out>
        handle = 0x7fffc40058b0
        session = <optimized out>
#3  0x00007ffff79865c0 in nice_component_emit_io_callback (agent=0x7fff6400a2a0, component=0x7fff6401a430, buf=0x7fff7dfeaa70 "\200o", buf_len=88) at component.c:954
  stream_id = 1
        component_id = 1
        io_callback = 0x555555593390 <janus_ice_cb_nice_recv>
        io_user_data = 0x7fff6401e1a0
        __func__ = "nice_component_emit_io_callback"
#4  0x00007ffff7991489 in component_io_cb (gsocket=<optimized out>, condition=<optimized out>, user_data=0x7fff64002e20) at agent.c:5556
        local_buf = "\200o\000\003\000\000\a\200@\247\214\256x\030d\226.n\321\375ϰ\017&lP\206\213\212z%Q\241LE\214\063\252\223q\222\066\215\353\255au\237F\202\025$=\002\275\226\216\216L$\237\241\301\000O\247\205\210\317:\255\271u\277\271c\024\233\060:$\246\307\032\342\002aX\201|\222U\340P\355\217Ak\177q>\377\205Δ\202ݾ\325qd\035\261\245\207+\026X1\373\061\277\355\376\354{IW\245|\324X\037`[S\\\252\317a\031\242\316\361\345\253\325\334B\306\002\024\346\277\066\243\067\016\037\356吶\260\251I\017\206\225\035F\274\306\321\067\266\004\202\240a4Y\004\202_&\332|\337\016e1_\352\301\304\v$\222\372\032f\020\224"...
        local_bufs = {buffer = 0x7fff7dfeaa70, size = 65535}
        local_message = {buffers = 0x7fff7dfeaa00, n_buffers = 1, from = 0x0, length = 88}
        retval = <optimized out>
        socket_source = 0x7fff64002e20
        component = 0x7fff6401a430
        agent = 0x7fff6400a2a0
        stream = 0x7fff64019fd0
        has_io_callback = <optimized out>
        remove_source = 0
        __func__ = "component_io_cb"
#5  0x00007ffff5088039 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007ffff745a285 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff745a650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff745a962 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x000055555558f013 in janus_ice_handle_thread (data=0x7fffc40058b0) at ice.c:1116
        handle = 0x7fffc40058b0
        __FUNCTION__ = "janus_ice_handle_thread"
#10 0x00007ffff7482195 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff5d0f6db in start_thread (arg=0x7fff7dffb700) at pthread_create.c:463
        pd = 0x7fff7dffb700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140735307298560, 4878660307081762848, 140735307296320, 0, 93824995254048, 140736741758336, -4878946181651621856, -4878647361755408352}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#12 0x00007ffff5a3888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 

```

**Comment by mqp** [comment]
Should be resolved via #48.
